### ISSUE TITLE
Cronjob/CI for web hosting

### ISSUE THREAD

**Issue by nrudesu** [GNUWeeb/www.gnuweeb.org#11]
When I was migrating this repository to [this](https://github.com/GNUWeeb/gnuweeb.github.io), I didn't find the gh-pages settings, so I assume that the website is hosted on nginx or apache. But I don't have any idea about this. How the website management or any else

- [x] we wait for [this problem](https://github.com/GNUWeeb/gnuweeb.github.io/issues/3) solved and get best conclusions
- [x] ensure the website have cronjob for pull or even better CI
- [ ] ensure they working
- [ ] done

**Comment by ammarfaizi2** [comment]
The website gnuweeb.org is hosted on a containerized machine, which I will share the access later today. We can manage to have CI/CD by using webhook feature.

**Comment by ammarfaizi2** [comment]
TODO:
- [x] Set webhook endpoint
- [x] Set automatic deployment for master branch

**Comment by ammarfaizi2** [comment]
I can't set webhook with the current permission, so I delay the fix for this at the moment.

**Comment by nrudesu** [comment]
> I can't set webhook with the current permission, so I delay the fix for this at the moment.

I restore your ownership, [here about details](https://github.com/GNUWeeb/old-website/issues/3#issuecomment-830216362)

**Comment by ammarfaizi2** [comment]
I will deploy a hot fix on internal webhook (private repo) tomorrow morning
if I get the time.

I have just gone away from my laptop. Good night.

**Comment by ammarfaizi2** [comment]
Every changes on master branch will be automatically deployed now. Who will test it?

**Comment by ammarfaizi2** [comment]
What CI are we going to use?
Lighthouse CI?
Ref: https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md

**Comment by irvanmalik48** [comment]
@ammarfaizi2 Yeah, Google products are usually nice to have, we'll probably wait for @nrudesu's opinion

**Comment by nrudesu** [comment]
Okay, just use Lighthouse CI.

Anyone who have permission for direcrly write repositor, can test it.*


*ofc when you have free time

>
