### ISSUE TITLE
Migrate icon

### ISSUE THREAD

**Issue by nrudesu** [GNUWeeb/www.gnuweeb.org#12]
migrate icon from [old repository](https://github.com/GNUWeeb/gnuweeb.github.io) to this

- [x] add icon (sorry I need for turn off gpg verify for while)
- [x] ensure changes sync at web hosting #11 
- [x] ensure website icon shows

**Comment by ammarfaizi2** [comment]
It is live now https://www.gnuweeb.org/

**Comment by ammarfaizi2** [comment]
I am closing this, kindly to re-open if you think the issue has not been resolved.
